import Head from 'next/head'

// API
import { getAllProducts } from '@/api/products'
import { getAllCategories } from '@/api/categories'

// Styles
import styles from '@/styles/Home.module.scss'
import { Footer } from '../components/organisms/Footer'


// Types
interface StoreItem { 
  id: number
  title: string
  category: string
  description: string
  image: string
  price: number
  rating: {
    count: number
    rate: number
  }
}

interface HomeProps {
  data: {
    products: StoreItem[]
    categories: string[]
  }
}

const Home = ({
  data
}: HomeProps) => {
  const { products, categories } = data
  
  console.log(categories)
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {/* Categories */}
        {categories.map((category, idx) => (
          <div key={idx}>
            {category}
          </div>
        ))}

        {/* Products */}
        {products.map((item, idx) => (
          <div key={idx}>
            <h4>{item?.title}</h4>
          </div>
        ))}
      </main>
      
      <Footer />
    </div>
  )
}

export default Home


export async function getServerSideProps() {
  const products = await getAllProducts()
  const categories = await getAllCategories()
  const data = {
    products,
    categories
  }
  
  return {
    props: { data }
  }
}